modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/AyameMC/Ayame-PaperDoll/issues"
license = "LGPL-3.0-or-later"

[[mods]]
modId = "ayame_paperdoll"
version = "${version}"
displayName = "Ayame PaperDoll"
displayURL = "https://github.com/AyameMC/Ayame-PaperDoll"
authors = '''
LucunJi(Original author)
HappyRespawnanchor
'''
credits = '''
Fallen_Breath
X-Green
altrisi
plusls
pertaz
'''
description = '''
Highly configurable PaperDoll mod.
Forked from Extra Player Renderer.
'''
logoFile = "icon.png"
updateJSONURL = "https://updatechecker.ayamemc.org/neoforge/ayame-paperdoll/update.json"
[[dependencies.ayame_paperdoll]]
modId = "neoforge"
type = "required"
versionRange = "[21.3.35-beta,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.ayame_paperdoll]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.3)"
ordering = "NONE"
side = "CLIENT"

#[[dependencies.ayame_paperdoll]]
#modId = "immediatelyfast"
#type = "incompatible"
#reason = '''
#The NeoForge version of ImmediatelyFast will break the cape rendering in Ayame PaperDoll. Please remove ImmediatelyFast.
#NeoForge版ImmediatelyFast会破坏Ayame纸娃娃的披风渲染，请移除ImmediatelyFast。
#'''
#ordering = "NONE"
#side = "BOTH"


[[mixins]]
config = "ayame-paperdoll.mixins.json"