modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/AyameMC/Ayame-PaperDoll/issues"
license = "LGPL-3.0-or-later"

[[mods]]
modId = "ayame_paperdoll"
version = "${version}"
displayName = "Ayame PaperDoll"
displayURL = "https://ayamemc.org/blog/tags/ayame-paperdoll"
authors = '''
LucunJi(Original author)
HappyRespawnanchor
'''
credits = '''
Fallen_Breath
X-Green
altrisi
plusls
pertaz
'''
description = '''
Highly configurable PaperDoll mod.
Forked from Extra Player Renderer.
'''
logoFile = "icon.png"
logoBlur = false
updateJSONURL = "https://api.modrinth.com/updates/ayame-paperdoll/forge_updates.json?neoforge=only"
[[dependencies.ayame_paperdoll]]
modId = "neoforge"
type = "required"
versionRange = "[21.3.58,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.ayame_paperdoll]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.3]"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "ayame-paperdoll.mixins.json"