modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "${mod_issues_url}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "${mod_homepage_url}"
authors = '''
LucunJi(Original author)
HappyRespawnanchor
'''
credits = '''
Fallen_Breath
X-Green
altrisi
plusls
pertaz
'''
description = '''${mod_description}'''
logoFile = "icon.png"
logoBlur = false
updateJSONURL = "https://api.modrinth.com/updates/ayame-paperdoll/forge_updates.json?neoforge=only"
[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${neoforge_minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "${mod_mixin_config}"